### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by tammyllf** [ccampo133/rds-logs-to-s3#1]
Hi Team,

I added this to my aws lambda, and I hit the following error.

>Response
>{
> "errorMessage": "'aws_region'",
> "errorType": "KeyError",
> "stackTrace": [
>   "  File \"/var/task/rds_logs_to_s3.py\", line 305, in lambda_handler\n    event['aws_region'],\n"
> ]
> }

If I removed it, the same error will happen on "min_size" (Line 307, event['min_size'])

please anyone help
Thanks

**Comment by ccampo133** [comment]
You need to pass the `aws_region` value as part of you CloudWatch event. Please see the documentation: https://github.com/ccampo133/rds-logs-to-s3#aws-lambda
